In [322]:
# Import package/module for data
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from jedi.api.refactoring import inline

In [323]:
dfPG = pd.read_csv("../train.csv")

In [324]:
dfPG.info()
dfPG.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7579 entries, 0 to 7578
Data columns (total 92 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fkl010h0_ANT             7578 non-null   float64
 1   fkl010h0_BAS             7576 non-null   float64
 2   fkl010h0_DAV             7576 non-null   float64
 3   fkl010h0_DOL             7578 non-null   float64
 4   fkl010h0_GVE             7578 non-null   float64
 5   fkl010h0_INT             7576 non-null   float64
 6   fkl010h0_LUG             7579 non-null   float64
 7   fkl010h0_SIO             7576 non-null   float64
 8   fkl010h0_STG             7575 non-null   float64
 9   fkl010h0_ZER             7578 non-null   float64
 10  fkl010h3_ANT             7576 non-null   float64
 11  fkl010h3_BAS             7579 non-null   float64
 12  fkl010h3_DAV             7576 non-null   float64
 13  fkl010h3_DOL             7579 non-null   float64
 14  fkl010h3_GVE             7579 non-null   float64
 15  fkl010h3_INT             7577 non-null   float64
 16  fkl010h3_LUG             7576 non-null   float64
 17  fkl010h3_SIO             7578 non-null   float64
 18  fkl010h3_STG             7576 non-null   float64
 19  fkl010h3_ZER             7579 non-null   float64
 20  gre000h0_ANT             7579 non-null   int64
 21  gre000h0_BAS             7577 non-null   float64
 22  gre000h0_DAV             7579 non-null   int64
 23  gre000h0_DOL             7577 non-null   float64
 24  gre000h0_GVE             7577 non-null   float64
 25  gre000h0_INT             7579 non-null   int64
 26  gre000h0_LUG             7579 non-null   int64
 27  gre000h0_SIO             7578 non-null   float64
 28  gre000h0_STG             7578 non-null   float64
 29  gre000h0_ZER             7576 non-null   float64
 30  pp0qffh0_BAS             7578 non-null   float64
 31  pp0qffh0_GVE             7579 non-null   float64
 32  pp0qffh0_INT             7577 non-null   float64
 33  pp0qffh0_LUG             7576 non-null   float64
 34  pp0qffh0_SIO             7577 non-null   float64
 35  prestah0_ANT             7579 non-null   float64
 36  prestah0_BAS             7578 non-null   float64
 37  prestah0_DAV             7577 non-null   float64
 38  prestah0_DOL             7577 non-null   float64
 39  prestah0_GVE             7577 non-null   float64
 40  prestah0_INT             7577 non-null   float64
 41  prestah0_LUG             7578 non-null   float64
 42  prestah0_SIO             7579 non-null   float64
 43  prestah0_STG             7576 non-null   float64
 44  prestah0_ZER             7577 non-null   float64
 45  rre150h0_ANT             7575 non-null   float64
 46  rre150h0_BAS             7577 non-null   float64
 47  rre150h0_DAV             7577 non-null   float64
 48  rre150h0_DOL             7579 non-null   float64
 49  rre150h0_GVE             7578 non-null   float64
 50  rre150h0_INT             7577 non-null   float64
 51  rre150h0_LUG             7579 non-null   float64
 52  rre150h0_SIO             7577 non-null   float64
 53  rre150h0_STG             7579 non-null   float64
 54  rre150h0_ZER             7578 non-null   float64
 55  sre000h0_ANT             7578 non-null   float64
 56  sre000h0_BAS             7578 non-null   float64
 57  sre000h0_DAV             7577 non-null   float64
 58  sre000h0_DOL             7579 non-null   int64
 59  sre000h0_GVE             7575 non-null   float64
 60  sre000h0_INT             7576 non-null   float64
 61  sre000h0_LUG             7575 non-null   float64
 62  sre000h0_SIO             7576 non-null   float64
 63  sre000h0_STG             7579 non-null   int64
 64  sre000h0_ZER             7579 non-null   int64
 65  tre200h0_ANT             7578 non-null   float64
 66  tre200h0_BAS             7575 non-null   float64
 67  tre200h0_DAV             7577 non-null   float64
 68  tre200h0_DOL             7577 non-null   float64
 69  tre200h0_GVE             7579 non-null   float64
 70  tre200h0_INT             7579 non-null   float64
 71  tre200h0_LUG             7578 non-null   float64
 72  tre200h0_SIO             7578 non-null   float64
 73  tre200h0_STG             7579 non-null   float64
 74  tre200h0_ZER             7577 non-null   float64
 75  ure200h0_ANT             7575 non-null   float64
 76  ure200h0_BAS             7576 non-null   float64
 77  ure200h0_DAV             7575 non-null   float64
 78  ure200h0_DOL             7577 non-null   float64
 79  ure200h0_GVE             7578 non-null   float64
 80  ure200h0_INT             7577 non-null   float64
 81  ure200h0_LUG             7576 non-null   float64
 82  ure200h0_SIO             7578 non-null   float64
 83  ure200h0_STG             7575 non-null   float64
 84  ure200h0_ZER             7579 non-null   float64
 85  tre200h0                 7577 non-null   float64
 86  tre200h0_lag24h          7575 non-null   float64
 87  target_tre200h0_plus12h  7577 non-null   float64
 88  target_tre200h0_plus24h  7578 non-null   float64
 89  target_tre200h0_plus48h  7578 non-null   float64
 90  hour                     7578 non-null   float64
 91  season                   7578 non-null   object
dtypes: float64(84), int64(7), object(1)
memory usage: 5.3+ MB

,fkl010h0_ANT,fkl010h0_BAS,fkl010h0_DAV,fkl010h0_DOL,fkl010h0_GVE,fkl010h0_INT,fkl010h0_LUG,fkl010h0_SIO,fkl010h0_STG,fkl010h0_ZER,...,ure200h0_SIO,ure200h0_STG,ure200h0_ZER,tre200h0,tre200h0_lag24h,target_tre200h0_plus12h,target_tre200h0_plus24h,target_tre200h0_plus48h,hour,season
0,1.3,2.1,0.8,8.3,1.0,0.6,0.6,0.5,3.4,0.9,...,84.4,76.0,74.0,12.2,8.5,17.5,10.3,10.0,5.0,Spring
1,3.8,0.8,3.8,14.0,6.9,0.5,2.9,0.6,2.0,1.8,...,87.6,96.3,67.4,4.3,8.9,12.1,1.5,6.3,3.0,Spring
2,1.1,2.0,0.1,10.5,2.1,1.3,1.1,1.7,0.9,1.1,...,81.9,96.5,65.8,-12.3,-7.6,-7.1,-3.5,-2.1,0.0,Winter
3,0.8,3.1,1.8,9.8,1.0,1.9,0.8,0.8,0.5,0.8,...,46.4,83.9,33.7,5.6,8.2,3.2,7.4,6.5,13.0,Autumn
4,4.4,1.6,4.3,2.9,2.2,2.8,6.3,5.4,1.0,2.8,...,39.4,65.7,44.7,20.7,19.2,15.7,21.9,23.9,11.0,Summer

In [325]:
dfPG['season'].unique

<bound method Series.unique of 0       Spring
1       Spring
2       Winter
3       Autumn
4       Summer
         ...
7574    Summer
7575    Spring
7576    Summer
7577    Spring
7578    Autumn
Name: season, Length: 7579, dtype: object>

In [326]:
pd.get_dummies(dfPG['season'])

      Autumn  Spring  Summer  Winter
0      False    True   False   False
1      False    True   False   False
2      False   False   False    True
3       True   False   False   False
4      False   False    True   False
...      ...     ...     ...     ...
7574   False   False    True   False
7575   False    True   False   False
7576   False   False    True   False
7577   False    True   False   False
7578    True   False   False   False

[7579 rows x 4 columns]

In [327]:
pd.concat([dfPG,  pd.get_dummies(dfPG['season'])], axis= 1)

,fkl010h0_ANT,fkl010h0_BAS,fkl010h0_DAV,fkl010h0_DOL,fkl010h0_GVE,fkl010h0_INT,fkl010h0_LUG,fkl010h0_SIO,fkl010h0_STG,fkl010h0_ZER,...,tre200h0_lag24h,target_tre200h0_plus12h,target_tre200h0_plus24h,target_tre200h0_plus48h,hour,season,Autumn,Spring,Summer,Winter
0,1.3,2.1,0.8,8.3,1.0,0.6,0.6,0.5,3.4,0.9,...,8.5,17.5,10.3,10.0,5.0,Spring,False,True,False,False
1,3.8,0.8,3.8,14.0,6.9,0.5,2.9,0.6,2.0,1.8,...,8.9,12.1,1.5,6.3,3.0,Spring,False,True,False,False
2,1.1,2.0,0.1,10.5,2.1,1.3,1.1,1.7,0.9,1.1,...,-7.6,-7.1,-3.5,-2.1,0.0,Winter,False,False,False,True
3,0.8,3.1,1.8,9.8,1.0,1.9,0.8,0.8,0.5,0.8,...,8.2,3.2,7.4,6.5,13.0,Autumn,True,False,False,False
4,4.4,1.6,4.3,2.9,2.2,2.8,6.3,5.4,1.0,2.8,...,19.2,15.7,21.9,23.9,11.0,Summer,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7574,3.2,0.8,3.1,3.9,1.5,1.9,1.9,4.5,1.1,0.7,...,17.8,16.3,19.7,25.2,18.0,Summer,False,False,True,False
7575,5.6,4.1,4.1,11.0,3.9,3.7,2.8,8.1,2.9,3.3,...,8.9,2.4,4.7,15.0,14.0,Spring,False,True,False,False
7576,1.5,1.6,1.0,8.0,0.7,0.7,1.3,0.8,1.6,1.1,...,17.4,19.6,15.4,16.2,6.0,Summer,False,False,True,False
7577,2.8,3.0,3.2,4.0,0.9,0.8,3.1,2.0,2.4,1.0,...,1.6,5.6,5.8,12.4,20.0,Spring,False,True,False,False
7578,0.9,0.7,1.8,10.0,0.5,1.7,1.4,0.5,0.5,0.9,...,10.6,11.9,11.3,11.8,20.0,Autumn,True,False,False,False

In [328]:
dfPG = dfPG.drop(columns = ['season'])

We need to do a shift on the date on each hour changing but now we only use a the dummies function

In [331]:
dfPG.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7579 entries, 0 to 7578
Data columns (total 91 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fkl010h0_ANT             7578 non-null   float64
 1   fkl010h0_BAS             7576 non-null   float64
 2   fkl010h0_DAV             7576 non-null   float64
 3   fkl010h0_DOL             7578 non-null   float64
 4   fkl010h0_GVE             7578 non-null   float64
 5   fkl010h0_INT             7576 non-null   float64
 6   fkl010h0_LUG             7579 non-null   float64
 7   fkl010h0_SIO             7576 non-null   float64
 8   fkl010h0_STG             7575 non-null   float64
 9   fkl010h0_ZER             7578 non-null   float64
 10  fkl010h3_ANT             7576 non-null   float64
 11  fkl010h3_BAS             7579 non-null   float64
 12  fkl010h3_DAV             7576 non-null   float64
 13  fkl010h3_DOL             7579 non-null   float64
 14  fkl010h3_GVE             7579 non-null   float64
 15  fkl010h3_INT             7577 non-null   float64
 16  fkl010h3_LUG             7576 non-null   float64
 17  fkl010h3_SIO             7578 non-null   float64
 18  fkl010h3_STG             7576 non-null   float64
 19  fkl010h3_ZER             7579 non-null   float64
 20  gre000h0_ANT             7579 non-null   int64
 21  gre000h0_BAS             7577 non-null   float64
 22  gre000h0_DAV             7579 non-null   int64
 23  gre000h0_DOL             7577 non-null   float64
 24  gre000h0_GVE             7577 non-null   float64
 25  gre000h0_INT             7579 non-null   int64
 26  gre000h0_LUG             7579 non-null   int64
 27  gre000h0_SIO             7578 non-null   float64
 28  gre000h0_STG             7578 non-null   float64
 29  gre000h0_ZER             7576 non-null   float64
 30  pp0qffh0_BAS             7578 non-null   float64
 31  pp0qffh0_GVE             7579 non-null   float64
 32  pp0qffh0_INT             7577 non-null   float64
 33  pp0qffh0_LUG             7576 non-null   float64
 34  pp0qffh0_SIO             7577 non-null   float64
 35  prestah0_ANT             7579 non-null   float64
 36  prestah0_BAS             7578 non-null   float64
 37  prestah0_DAV             7577 non-null   float64
 38  prestah0_DOL             7577 non-null   float64
 39  prestah0_GVE             7577 non-null   float64
 40  prestah0_INT             7577 non-null   float64
 41  prestah0_LUG             7578 non-null   float64
 42  prestah0_SIO             7579 non-null   float64
 43  prestah0_STG             7576 non-null   float64
 44  prestah0_ZER             7577 non-null   float64
 45  rre150h0_ANT             7575 non-null   float64
 46  rre150h0_BAS             7577 non-null   float64
 47  rre150h0_DAV             7577 non-null   float64
 48  rre150h0_DOL             7579 non-null   float64
 49  rre150h0_GVE             7578 non-null   float64
 50  rre150h0_INT             7577 non-null   float64
 51  rre150h0_LUG             7579 non-null   float64
 52  rre150h0_SIO             7577 non-null   float64
 53  rre150h0_STG             7579 non-null   float64
 54  rre150h0_ZER             7578 non-null   float64
 55  sre000h0_ANT             7578 non-null   float64
 56  sre000h0_BAS             7578 non-null   float64
 57  sre000h0_DAV             7577 non-null   float64
 58  sre000h0_DOL             7579 non-null   int64
 59  sre000h0_GVE             7575 non-null   float64
 60  sre000h0_INT             7576 non-null   float64
 61  sre000h0_LUG             7575 non-null   float64
 62  sre000h0_SIO             7576 non-null   float64
 63  sre000h0_STG             7579 non-null   int64
 64  sre000h0_ZER             7579 non-null   int64
 65  tre200h0_ANT             7578 non-null   float64
 66  tre200h0_BAS             7575 non-null   float64
 67  tre200h0_DAV             7577 non-null   float64
 68  tre200h0_DOL             7577 non-null   float64
 69  tre200h0_GVE             7579 non-null   float64
 70  tre200h0_INT             7579 non-null   float64
 71  tre200h0_LUG             7578 non-null   float64
 72  tre200h0_SIO             7578 non-null   float64
 73  tre200h0_STG             7579 non-null   float64
 74  tre200h0_ZER             7577 non-null   float64
 75  ure200h0_ANT             7575 non-null   float64
 76  ure200h0_BAS             7576 non-null   float64
 77  ure200h0_DAV             7575 non-null   float64
 78  ure200h0_DOL             7577 non-null   float64
 79  ure200h0_GVE             7578 non-null   float64
 80  ure200h0_INT             7577 non-null   float64
 81  ure200h0_LUG             7576 non-null   float64
 82  ure200h0_SIO             7578 non-null   float64
 83  ure200h0_STG             7575 non-null   float64
 84  ure200h0_ZER             7579 non-null   float64
 85  tre200h0                 7577 non-null   float64
 86  tre200h0_lag24h          7575 non-null   float64
 87  target_tre200h0_plus12h  7577 non-null   float64
 88  target_tre200h0_plus24h  7578 non-null   float64
 89  target_tre200h0_plus48h  7578 non-null   float64
 90  hour                     7578 non-null   float64
dtypes: float64(84), int64(7)
memory usage: 5.3 MB

In [ ]:
dfPG = dfPG.dropna()

In [334]:
dfNAN = dfPG[dfPG == np.isnan]
dfNAN

,fkl010h0_ANT,fkl010h0_BAS,fkl010h0_DAV,fkl010h0_DOL,fkl010h0_GVE,fkl010h0_INT,fkl010h0_LUG,fkl010h0_SIO,fkl010h0_STG,fkl010h0_ZER,...,ure200h0_LUG,ure200h0_SIO,ure200h0_STG,ure200h0_ZER,tre200h0,tre200h0_lag24h,target_tre200h0_plus12h,target_tre200h0_plus24h,target_tre200h0_plus48h,hour
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [335]:
print(np.isnan(dfPG).sum())

fkl010h0_ANT               1
fkl010h0_BAS               3
fkl010h0_DAV               3
fkl010h0_DOL               1
fkl010h0_GVE               1
                          ..
tre200h0_lag24h            4
target_tre200h0_plus12h    2
target_tre200h0_plus24h    1
target_tre200h0_plus48h    1
hour                       1
Length: 91, dtype: int64

In [ ]:
dfPG.info()

In [ ]:
from matplotlib.cm import get_cmap
import matplotlib.pyplot as plt
cmap = plt.get_cmap('Set2')
dfPG = dfPG.select_dtypes(include="number")
n = len(dfPG.columns)

cmap = plt.get_cmap('Set2')

# Création des sous-graphes
fig, axes = plt.subplots(n, 1, figsize=(5 , 5*n))

# Si axes est un tableau 1D, pas besoin de squeeze=False
for i, col in enumerate(dfPG.columns):
    box = axes[i].boxplot(dfPG[col], patch_artist=True)
    axes[i].set_title(col)
    axes[i].set_ylabel("")  # Supprime le label Y
    axes[i].grid(True)

    # Appliquer une couleur automatique
    for patch in box['boxes']:
        patch.set_facecolor(cmap(i % cmap.N))  # Assure que l'index reste dans la palette

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

dfPG.boxplot(column=["hour"], grid=False, vert=False, patch_artist=True)
plt.title("Boxplot horizontal des colonnes reference_timestamp")
plt.show()

dfPG.plot.scatter(x='reference_timestamp_num', y='target_tre200h0_plus12h', alpha=0.7, edgecolors='w')
plt.title("Scatter Plot entre time et target")
plt.grid(True)
plt.show()

In [ ]:
X = dfPG.drop(["target_tre200h0_plus12h","target_tre200h0_plus24h", "target_tre200h0_plus48h"], axis = 1)
y1 = dfPG["target_tre200h0_plus12h"]
y2 = dfPG["target_tre200h0_plus24h"]
y3 = dfPG["target_tre200h0_plus48h"]
X.info()

##### We treat y1 = dfPG["target_tre200h0_plus12h"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size = .2, random_state = 12)

##### We want to find the best coefficient with lasso
* we use a pipeline to have better performance
* we use a standard scaler to have not too much variance between the values display on a plot x y

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
lasso = Lasso(alpha = 0.1, fit_intercept = True)

lasso_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('lasso', lasso)
])

In [ ]:
lasso_pipe.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import root_mean_squared_error, r2_score

print(f"Variance de y : {np.var(y1)}" )
print(f"Ecart-type de y : {np.std(y1)}")
y_hat = lasso_pipe.predict(X_train)
print(f"MSRE_train : {root_mean_squared_error(y_train, y_hat)}")
y_hat_test = lasso_pipe.predict(X_test)
print(f"MSRE_test : {root_mean_squared_error(y_test, y_hat_test)}")

**En regression on utilise R2 score**
* En régression, on ne parle pas d'accuracy comme en classification. On utilise plutôt le R² score, qui indique la proportion de la variance expliquée par le modèle.

In [ ]:
lasso_gride = np.linspace(1, 1e6) # tunning parameters to find the main coefficient

In [ ]:
coefs = []
for alpha in lasso_gride:
    lasso_pipe.set_params(lasso__alpha=alpha, lasso__fit_intercept=True)
    lasso_pipe.fit(X_train, y_train)
    coefs.append(lasso_pipe.named_steps['lasso'].coef_)

In [ ]:
def affichage_lasso_Coef_with_alpha(grid_alpha, X_train, y_train):
    coef = []
    for alpha in grid_alpha:
        lp =lasso_pipe.set_params(lasso__alpha=alpha, lasso__fit_intercept=True).fit(X_train, y_train)
        coef.append(lp.named_steps['lasso'].coef_)

    coef_lp = np.array(coef)

    plt.figure(figsize=(10,6))
    for i in range(coef_lp.shape[1]):
        plt.plot(grid_alpha, coef_lp[:, i], marker="o", label=f"Feature {i}")
    plt.xscale("log")
    plt.xlabel("Alpha (log scale)")
    plt.ylabel("Coefficient value")
    plt.title("Évolution des coefficients lasso selon alpha")
    plt.legend(X_train.columns, loc='upper right', bbox_to_anchor = (2.5, 1))
    plt.legend(bbox_to_anchor=(1, 1), loc="upper left")
    plt.show()

In [ ]:
affichage_lasso_Coef_with_alpha(lasso_gride, X_train, y_train)

###  CV for Lasso

In [ ]:
from sklearn.model_selection import KFold
folds = KFold(n_splits=10 , shuffle=True, random_state=42)

In [ ]:
#lasso_gride = np.linspace(1e-2, 1e6)
#lasso_gride = 10**np.linspace(0, 6, num=30)
lasso_gride = np.geomspace(1, 1e6, num=30)
dictAlpha_lasso = {
    "lasso__alpha": lasso_gride,
}
dictAlpha_lasso['lasso__alpha']
params_lasso = {"lasso__alpha" : lasso_gride}

Create a dictionary with the key-value pair `"lasso__alpha"`, `lasso_grid`. What is the use of this object?

In [ ]:
lasso_pipe.get_params()

In [ ]:
from sklearn.model_selection import GridSearchCV
gscv_lasso = GridSearchCV(estimator=lasso_pipe, param_grid=dictAlpha_lasso, scoring="neg_mean_squared_error", cv=folds)

Run the cross-validation by calling the `fit` method of the **cross-validation object** that you created at the point before.

In [ ]:
lassoCV = gscv_lasso.fit(X_train, y_train)

We want to plot the cross-validation error against different values of the penalty parameter

In [ ]:
df_lasso_cv_results_ = pd.DataFrame(lassoCV.cv_results_)
df_lasso_cv_results_.info()
df_lasso_cv_results_.head(5)

Run the cross-validation by calling the `fit` method of the **cross-validation object** that you created at the point before.

In [ ]:
lassoCV.fit(X_train, y_train)

We want to plot the cross-validation error against different values of the penalty parameter.

In [ ]:
# Choose best model that minimizes the cv_err
mean_scores = -lassoCV.cv_results_["mean_test_score"]
se_scores = lassoCV.cv_results_["std_test_score"] / np.sqrt(lassoCV.n_splits_)
alphas = lassoCV.cv_results_["param_lasso__alpha"].data

best_index = np.argmin(mean_scores)
min_alpha_lasso = alphas[best_index]

threshold_lasso = mean_scores[best_index] + se_scores[best_index]
one_se_rule_alpha_lasso = np.max(alphas[mean_scores <= threshold_lasso])

print("Minimum alpha:", min_alpha_lasso)
print("1-SD alpha:", one_se_rule_alpha_lasso)
print("Best score for lasso:", np.sqrt(np.min(mean_scores)))

In [ ]:
plt.errorbar(x=lasso_gride, y=mean_scores, yerr = se_scores, fmt='o', capsize=3)

plt.axvline(min_alpha_lasso, ls='dotted', color="grey")
plt.axvline(one_se_rule_alpha_lasso, ls='dotted', color="grey")
plt.axhline(threshold_lasso, ls='dotted', color="grey")

plt.title("Lasso regressor CV error")
plt.xlabel('log(alpha)')
plt.ylabel('Mean Squared Error')
plt.xscale('log')
plt.show()

### Compute performance the best models

In [ ]:
# Refit best lasso on whole training data and evaluate on test
lasso_pipe.set_params(lasso__alpha = one_se_rule_alpha_lasso)
lasso_pipe.fit(X_train, y_train)

y_test_pred = lasso_pipe.predict(X_test)
root_mean_squared_error(y_test, y_test_pred)
# a battre 09952958101565458

**Alpha qui marche le mieux**
* lasso_pipe.set_params(lasso__alpha = one_se_rule_alpha_lasso)

In [ ]:
print(f"L'alpha qui marche le mieux {one_se_rule_alpha_lasso}")

In [ ]:
from sklearn.metrics import r2_score

print(f"Train R2_score (accuracy):{r2_score(y_train, y_hat)}")
print(f"Test R2_score (accuracy):{r2_score(y_test, y_hat_test)}")

In [ ]:
# Show predictor that are ignored by lasso
columnsNotWanted = X.columns[lasso_pipe.named_steps['lasso'].coef_ == 0].to_list()
columnsNotWanted

In [ ]:
# Show predictor that are not ignored by lasso
X.columns[lasso_pipe.named_steps['lasso'].coef_ != 0].to_list()

Ce sont les coefficients qui comptent pour notre classification

## Prediction sur les y1, y2, y3 avec les valeurs de

In [287]:
df_challenge = pd.read_csv("../test.csv")
df_challenge.info()
df_challenge.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3247 entries, 0 to 3246
Data columns (total 90 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               3247 non-null   int64
 1   fkl010h0_ANT     3247 non-null   float64
 2   fkl010h0_BAS     3247 non-null   float64
 3   fkl010h0_DAV     3247 non-null   float64
 4   fkl010h0_DOL     3247 non-null   float64
 5   fkl010h0_GVE     3247 non-null   float64
 6   fkl010h0_INT     3247 non-null   float64
 7   fkl010h0_LUG     3247 non-null   float64
 8   fkl010h0_SIO     3247 non-null   float64
 9   fkl010h0_STG     3247 non-null   float64
 10  fkl010h0_ZER     3247 non-null   float64
 11  fkl010h3_ANT     3247 non-null   float64
 12  fkl010h3_BAS     3247 non-null   float64
 13  fkl010h3_DAV     3247 non-null   float64
 14  fkl010h3_DOL     3247 non-null   float64
 15  fkl010h3_GVE     3247 non-null   float64
 16  fkl010h3_INT     3247 non-null   float64
 17  fkl010h3_LUG     3247 non-null   float64
 18  fkl010h3_SIO     3247 non-null   float64
 19  fkl010h3_STG     3247 non-null   float64
 20  fkl010h3_ZER     3247 non-null   float64
 21  gre000h0_ANT     3247 non-null   int64
 22  gre000h0_BAS     3247 non-null   int64
 23  gre000h0_DAV     3247 non-null   int64
 24  gre000h0_DOL     3247 non-null   int64
 25  gre000h0_GVE     3247 non-null   int64
 26  gre000h0_INT     3247 non-null   int64
 27  gre000h0_LUG     3247 non-null   int64
 28  gre000h0_SIO     3247 non-null   int64
 29  gre000h0_STG     3247 non-null   int64
 30  gre000h0_ZER     3247 non-null   int64
 31  pp0qffh0_BAS     3247 non-null   float64
 32  pp0qffh0_GVE     3247 non-null   float64
 33  pp0qffh0_INT     3247 non-null   float64
 34  pp0qffh0_LUG     3247 non-null   float64
 35  pp0qffh0_SIO     3247 non-null   float64
 36  prestah0_ANT     3247 non-null   float64
 37  prestah0_BAS     3247 non-null   float64
 38  prestah0_DAV     3247 non-null   float64
 39  prestah0_DOL     3247 non-null   float64
 40  prestah0_GVE     3247 non-null   float64
 41  prestah0_INT     3247 non-null   float64
 42  prestah0_LUG     3247 non-null   float64
 43  prestah0_SIO     3247 non-null   float64
 44  prestah0_STG     3247 non-null   float64
 45  prestah0_ZER     3247 non-null   float64
 46  rre150h0_ANT     3247 non-null   float64
 47  rre150h0_BAS     3247 non-null   float64
 48  rre150h0_DAV     3247 non-null   float64
 49  rre150h0_DOL     3247 non-null   float64
 50  rre150h0_GVE     3247 non-null   float64
 51  rre150h0_INT     3247 non-null   float64
 52  rre150h0_LUG     3247 non-null   float64
 53  rre150h0_SIO     3247 non-null   float64
 54  rre150h0_STG     3247 non-null   float64
 55  rre150h0_ZER     3247 non-null   float64
 56  sre000h0_ANT     3247 non-null   int64
 57  sre000h0_BAS     3247 non-null   int64
 58  sre000h0_DAV     3247 non-null   int64
 59  sre000h0_DOL     3247 non-null   int64
 60  sre000h0_GVE     3247 non-null   int64
 61  sre000h0_INT     3247 non-null   int64
 62  sre000h0_LUG     3247 non-null   int64
 63  sre000h0_SIO     3247 non-null   int64
 64  sre000h0_STG     3247 non-null   int64
 65  sre000h0_ZER     3247 non-null   int64
 66  tre200h0_ANT     3247 non-null   float64
 67  tre200h0_BAS     3247 non-null   float64
 68  tre200h0_DAV     3247 non-null   float64
 69  tre200h0_DOL     3247 non-null   float64
 70  tre200h0_GVE     3247 non-null   float64
 71  tre200h0_INT     3247 non-null   float64
 72  tre200h0_LUG     3247 non-null   float64
 73  tre200h0_SIO     3247 non-null   float64
 74  tre200h0_STG     3247 non-null   float64
 75  tre200h0_ZER     3247 non-null   float64
 76  ure200h0_ANT     3247 non-null   float64
 77  ure200h0_BAS     3247 non-null   float64
 78  ure200h0_DAV     3247 non-null   float64
 79  ure200h0_DOL     3247 non-null   float64
 80  ure200h0_GVE     3247 non-null   float64
 81  ure200h0_INT     3247 non-null   float64
 82  ure200h0_LUG     3247 non-null   float64
 83  ure200h0_SIO     3247 non-null   float64
 84  ure200h0_STG     3247 non-null   float64
 85  ure200h0_ZER     3247 non-null   float64
 86  tre200h0         3247 non-null   float64
 87  tre200h0_lag24h  3247 non-null   float64
 88  hour             3247 non-null   int64
 89  season           3247 non-null   object
dtypes: float64(67), int64(22), object(1)
memory usage: 2.2+ MB

,Id,fkl010h0_ANT,fkl010h0_BAS,fkl010h0_DAV,fkl010h0_DOL,fkl010h0_GVE,fkl010h0_INT,fkl010h0_LUG,fkl010h0_SIO,fkl010h0_STG,...,ure200h0_GVE,ure200h0_INT,ure200h0_LUG,ure200h0_SIO,ure200h0_STG,ure200h0_ZER,tre200h0,tre200h0_lag24h,hour,season
0,1,8.1,1.7,4.5,13.5,6.8,2.2,0.6,0.6,4.5,...,87.1,96.2,62.5,92.6,85.7,72.9,5.5,5.9,13,Winter
1,2,0.9,1.8,1.3,3.1,0.9,1.6,0.8,0.6,0.8,...,79.3,76.4,59.4,69.4,77.4,33.7,1.9,5.5,18,Winter
2,3,2.9,2.1,0.8,5.8,0.7,0.5,1.1,0.9,4.3,...,72.7,94.3,80.1,84.2,84.5,74.5,17.7,17.5,0,Spring
3,4,5.4,2.6,3.2,5.7,5.2,2.3,0.5,8.2,1.7,...,46.1,54.7,48.4,35.6,60.2,34.8,7.5,4.4,16,Spring
4,5,0.9,0.6,1.1,1.7,0.5,0.7,0.5,0.5,0.6,...,86.5,85.9,81.7,74.3,64.2,65.6,11.7,14.6,1,Spring

In [ ]:
import re
def num_dat(x):
    # Exemple de chaîne contenant une date
    #2015-01-17 09:00:00
    # Regex pour capturer la date et la transformer
    match = re.search(r'(\d{4})-(\d{2})-(\d{2}) (\d{2})', x)  # find the date from the separator
    # we only get the two number of the time the other are 00 always
    if match:
        date_num = ''.join(match.groups())  # join all
        return date_num  # return the date

In [295]:
columnsNotWanted = ['fkl010h0_ANT',
 'fkl010h0_BAS',
 'fkl010h0_DAV',
 'fkl010h0_DOL',
 'fkl010h0_GVE',
 'fkl010h0_LUG',
 'fkl010h0_SIO',
 'fkl010h0_STG',
 'fkl010h0_ZER',
 'fkl010h3_ANT',
 'fkl010h3_BAS',
 'fkl010h3_DAV',
 'fkl010h3_DOL',
 'fkl010h3_GVE',
 'fkl010h3_INT',
 'fkl010h3_LUG',
 'fkl010h3_STG',
 'fkl010h3_ZER',
 'gre000h0_ANT',
 'gre000h0_BAS',
 'gre000h0_DAV',
 'gre000h0_DOL',
 'gre000h0_GVE',
 'gre000h0_INT',
 'gre000h0_LUG',
 'gre000h0_SIO',
 'gre000h0_STG',
 'gre000h0_ZER',
 'pp0qffh0_BAS',
 'pp0qffh0_GVE',
 'pp0qffh0_INT',
 'pp0qffh0_LUG',
 'pp0qffh0_SIO',
 'prestah0_ANT',
 'prestah0_BAS',
 'prestah0_DAV',
 'prestah0_DOL',
 'prestah0_GVE',
 'prestah0_INT',
 'prestah0_LUG',
 'prestah0_SIO',
 'prestah0_STG',
 'prestah0_ZER',
 'rre150h0_ANT',
 'rre150h0_BAS',
 'rre150h0_DAV',
 'rre150h0_DOL',
 'rre150h0_GVE',
 'rre150h0_INT',
 'rre150h0_LUG',
 'rre150h0_SIO',
 'rre150h0_STG',
 'rre150h0_ZER',
 'sre000h0_ANT',
 'sre000h0_BAS',
 'sre000h0_DAV',
 'sre000h0_DOL',
 'sre000h0_GVE',
 'sre000h0_INT',
 'sre000h0_SIO',
 'sre000h0_STG',
 'sre000h0_ZER',
 'tre200h0_ANT',
 'tre200h0_BAS',
 'tre200h0_DAV',
 'tre200h0_GVE',
 'tre200h0_INT',
 'tre200h0_SIO',
 'tre200h0_ZER',
 'ure200h0_BAS',
 'ure200h0_DOL',
 'ure200h0_GVE',
 'ure200h0_INT',
 'ure200h0_LUG',
 'ure200h0_SIO',
 'ure200h0_STG',
 'ure200h0_ZER',
 'tre200h0',
 'tre200h0_lag24h']

_IncompleteInputError: incomplete input (1804855659.py, line 79)

In [ ]:
dfPG['reference_timestamp_num'].unique()

In [304]:
def preTraitement(dfPG):
    dfPG = pd.concat([dfPG, pd.get_dummies(dfPG['season'])], axis=1)
    dfPG = dfPG.drop(columns=['season'])
    dfPG = dfPG.dropna()
    #x = dfPG.drop(columnsNotWanted,axis=1)
    x = dfPG.drop(["target_tre200h0_plus12h", "target_tre200h0_plus24h", "target_tre200h0_plus48h"], axis=1)
    y1 = dfPG["target_tre200h0_plus12h"]
    y2 = dfPG["target_tre200h0_plus24h"]
    y3 = dfPG["target_tre200h0_plus48h"]
    return {
        'X': x,
        'y1': y1,
        'y2': y2,
        'y3': y3
    }

In [308]:
def preTraitement_test(df_test):
    df_test = pd.concat([df_test, pd.get_dummies(df_test['season'])], axis=1)
    df_test = df_test.drop(columns=['season', 'Id'])
    #df_test = df_test.drop(columnsNotWanted2,axis=1)
    df_test = df_test.dropna()
    #X = df_test.drop(columnsNotWanted2,axis=1)
    return {
        'X':df_test
    }

In [309]:
data_train = preTraitement(dfPG)
X_train = data_train['X']
y1_train = data_train['y1']
y2_train = data_train['y2']
y3_train = data_train['y3']
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7430 entries, 0 to 7578
Data columns (total 92 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fkl010h0_ANT     7430 non-null   float64
 1   fkl010h0_BAS     7430 non-null   float64
 2   fkl010h0_DAV     7430 non-null   float64
 3   fkl010h0_DOL     7430 non-null   float64
 4   fkl010h0_GVE     7430 non-null   float64
 5   fkl010h0_INT     7430 non-null   float64
 6   fkl010h0_LUG     7430 non-null   float64
 7   fkl010h0_SIO     7430 non-null   float64
 8   fkl010h0_STG     7430 non-null   float64
 9   fkl010h0_ZER     7430 non-null   float64
 10  fkl010h3_ANT     7430 non-null   float64
 11  fkl010h3_BAS     7430 non-null   float64
 12  fkl010h3_DAV     7430 non-null   float64
 13  fkl010h3_DOL     7430 non-null   float64
 14  fkl010h3_GVE     7430 non-null   float64
 15  fkl010h3_INT     7430 non-null   float64
 16  fkl010h3_LUG     7430 non-null   float64
 17  fkl010h3_SIO     7430 non-null   float64
 18  fkl010h3_STG     7430 non-null   float64
 19  fkl010h3_ZER     7430 non-null   float64
 20  gre000h0_ANT     7430 non-null   int64
 21  gre000h0_BAS     7430 non-null   float64
 22  gre000h0_DAV     7430 non-null   int64
 23  gre000h0_DOL     7430 non-null   float64
 24  gre000h0_GVE     7430 non-null   float64
 25  gre000h0_INT     7430 non-null   int64
 26  gre000h0_LUG     7430 non-null   int64
 27  gre000h0_SIO     7430 non-null   float64
 28  gre000h0_STG     7430 non-null   float64
 29  gre000h0_ZER     7430 non-null   float64
 30  pp0qffh0_BAS     7430 non-null   float64
 31  pp0qffh0_GVE     7430 non-null   float64
 32  pp0qffh0_INT     7430 non-null   float64
 33  pp0qffh0_LUG     7430 non-null   float64
 34  pp0qffh0_SIO     7430 non-null   float64
 35  prestah0_ANT     7430 non-null   float64
 36  prestah0_BAS     7430 non-null   float64
 37  prestah0_DAV     7430 non-null   float64
 38  prestah0_DOL     7430 non-null   float64
 39  prestah0_GVE     7430 non-null   float64
 40  prestah0_INT     7430 non-null   float64
 41  prestah0_LUG     7430 non-null   float64
 42  prestah0_SIO     7430 non-null   float64
 43  prestah0_STG     7430 non-null   float64
 44  prestah0_ZER     7430 non-null   float64
 45  rre150h0_ANT     7430 non-null   float64
 46  rre150h0_BAS     7430 non-null   float64
 47  rre150h0_DAV     7430 non-null   float64
 48  rre150h0_DOL     7430 non-null   float64
 49  rre150h0_GVE     7430 non-null   float64
 50  rre150h0_INT     7430 non-null   float64
 51  rre150h0_LUG     7430 non-null   float64
 52  rre150h0_SIO     7430 non-null   float64
 53  rre150h0_STG     7430 non-null   float64
 54  rre150h0_ZER     7430 non-null   float64
 55  sre000h0_ANT     7430 non-null   float64
 56  sre000h0_BAS     7430 non-null   float64
 57  sre000h0_DAV     7430 non-null   float64
 58  sre000h0_DOL     7430 non-null   int64
 59  sre000h0_GVE     7430 non-null   float64
 60  sre000h0_INT     7430 non-null   float64
 61  sre000h0_LUG     7430 non-null   float64
 62  sre000h0_SIO     7430 non-null   float64
 63  sre000h0_STG     7430 non-null   int64
 64  sre000h0_ZER     7430 non-null   int64
 65  tre200h0_ANT     7430 non-null   float64
 66  tre200h0_BAS     7430 non-null   float64
 67  tre200h0_DAV     7430 non-null   float64
 68  tre200h0_DOL     7430 non-null   float64
 69  tre200h0_GVE     7430 non-null   float64
 70  tre200h0_INT     7430 non-null   float64
 71  tre200h0_LUG     7430 non-null   float64
 72  tre200h0_SIO     7430 non-null   float64
 73  tre200h0_STG     7430 non-null   float64
 74  tre200h0_ZER     7430 non-null   float64
 75  ure200h0_ANT     7430 non-null   float64
 76  ure200h0_BAS     7430 non-null   float64
 77  ure200h0_DAV     7430 non-null   float64
 78  ure200h0_DOL     7430 non-null   float64
 79  ure200h0_GVE     7430 non-null   float64
 80  ure200h0_INT     7430 non-null   float64
 81  ure200h0_LUG     7430 non-null   float64
 82  ure200h0_SIO     7430 non-null   float64
 83  ure200h0_STG     7430 non-null   float64
 84  ure200h0_ZER     7430 non-null   float64
 85  tre200h0         7430 non-null   float64
 86  tre200h0_lag24h  7430 non-null   float64
 87  hour             7430 non-null   float64
 88  Autumn           7430 non-null   bool
 89  Spring           7430 non-null   bool
 90  Summer           7430 non-null   bool
 91  Winter           7430 non-null   bool
dtypes: bool(4), float64(81), int64(7)
memory usage: 5.1 MB

In [310]:
data_test = preTraitement_test(df_challenge)
X_test = data_test['X']
X_test.info()
X_test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3247 entries, 0 to 3246
Data columns (total 92 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fkl010h0_ANT     3247 non-null   float64
 1   fkl010h0_BAS     3247 non-null   float64
 2   fkl010h0_DAV     3247 non-null   float64
 3   fkl010h0_DOL     3247 non-null   float64
 4   fkl010h0_GVE     3247 non-null   float64
 5   fkl010h0_INT     3247 non-null   float64
 6   fkl010h0_LUG     3247 non-null   float64
 7   fkl010h0_SIO     3247 non-null   float64
 8   fkl010h0_STG     3247 non-null   float64
 9   fkl010h0_ZER     3247 non-null   float64
 10  fkl010h3_ANT     3247 non-null   float64
 11  fkl010h3_BAS     3247 non-null   float64
 12  fkl010h3_DAV     3247 non-null   float64
 13  fkl010h3_DOL     3247 non-null   float64
 14  fkl010h3_GVE     3247 non-null   float64
 15  fkl010h3_INT     3247 non-null   float64
 16  fkl010h3_LUG     3247 non-null   float64
 17  fkl010h3_SIO     3247 non-null   float64
 18  fkl010h3_STG     3247 non-null   float64
 19  fkl010h3_ZER     3247 non-null   float64
 20  gre000h0_ANT     3247 non-null   int64
 21  gre000h0_BAS     3247 non-null   int64
 22  gre000h0_DAV     3247 non-null   int64
 23  gre000h0_DOL     3247 non-null   int64
 24  gre000h0_GVE     3247 non-null   int64
 25  gre000h0_INT     3247 non-null   int64
 26  gre000h0_LUG     3247 non-null   int64
 27  gre000h0_SIO     3247 non-null   int64
 28  gre000h0_STG     3247 non-null   int64
 29  gre000h0_ZER     3247 non-null   int64
 30  pp0qffh0_BAS     3247 non-null   float64
 31  pp0qffh0_GVE     3247 non-null   float64
 32  pp0qffh0_INT     3247 non-null   float64
 33  pp0qffh0_LUG     3247 non-null   float64
 34  pp0qffh0_SIO     3247 non-null   float64
 35  prestah0_ANT     3247 non-null   float64
 36  prestah0_BAS     3247 non-null   float64
 37  prestah0_DAV     3247 non-null   float64
 38  prestah0_DOL     3247 non-null   float64
 39  prestah0_GVE     3247 non-null   float64
 40  prestah0_INT     3247 non-null   float64
 41  prestah0_LUG     3247 non-null   float64
 42  prestah0_SIO     3247 non-null   float64
 43  prestah0_STG     3247 non-null   float64
 44  prestah0_ZER     3247 non-null   float64
 45  rre150h0_ANT     3247 non-null   float64
 46  rre150h0_BAS     3247 non-null   float64
 47  rre150h0_DAV     3247 non-null   float64
 48  rre150h0_DOL     3247 non-null   float64
 49  rre150h0_GVE     3247 non-null   float64
 50  rre150h0_INT     3247 non-null   float64
 51  rre150h0_LUG     3247 non-null   float64
 52  rre150h0_SIO     3247 non-null   float64
 53  rre150h0_STG     3247 non-null   float64
 54  rre150h0_ZER     3247 non-null   float64
 55  sre000h0_ANT     3247 non-null   int64
 56  sre000h0_BAS     3247 non-null   int64
 57  sre000h0_DAV     3247 non-null   int64
 58  sre000h0_DOL     3247 non-null   int64
 59  sre000h0_GVE     3247 non-null   int64
 60  sre000h0_INT     3247 non-null   int64
 61  sre000h0_LUG     3247 non-null   int64
 62  sre000h0_SIO     3247 non-null   int64
 63  sre000h0_STG     3247 non-null   int64
 64  sre000h0_ZER     3247 non-null   int64
 65  tre200h0_ANT     3247 non-null   float64
 66  tre200h0_BAS     3247 non-null   float64
 67  tre200h0_DAV     3247 non-null   float64
 68  tre200h0_DOL     3247 non-null   float64
 69  tre200h0_GVE     3247 non-null   float64
 70  tre200h0_INT     3247 non-null   float64
 71  tre200h0_LUG     3247 non-null   float64
 72  tre200h0_SIO     3247 non-null   float64
 73  tre200h0_STG     3247 non-null   float64
 74  tre200h0_ZER     3247 non-null   float64
 75  ure200h0_ANT     3247 non-null   float64
 76  ure200h0_BAS     3247 non-null   float64
 77  ure200h0_DAV     3247 non-null   float64
 78  ure200h0_DOL     3247 non-null   float64
 79  ure200h0_GVE     3247 non-null   float64
 80  ure200h0_INT     3247 non-null   float64
 81  ure200h0_LUG     3247 non-null   float64
 82  ure200h0_SIO     3247 non-null   float64
 83  ure200h0_STG     3247 non-null   float64
 84  ure200h0_ZER     3247 non-null   float64
 85  tre200h0         3247 non-null   float64
 86  tre200h0_lag24h  3247 non-null   float64
 87  hour             3247 non-null   int64
 88  Autumn           3247 non-null   bool
 89  Spring           3247 non-null   bool
 90  Summer           3247 non-null   bool
 91  Winter           3247 non-null   bool
dtypes: bool(4), float64(67), int64(21)
memory usage: 2.2 MB

,fkl010h0_ANT,fkl010h0_BAS,fkl010h0_DAV,fkl010h0_DOL,fkl010h0_GVE,fkl010h0_INT,fkl010h0_LUG,fkl010h0_SIO,fkl010h0_STG,fkl010h0_ZER,...,ure200h0_SIO,ure200h0_STG,ure200h0_ZER,tre200h0,tre200h0_lag24h,hour,Autumn,Spring,Summer,Winter
0,8.1,1.7,4.5,13.5,6.8,2.2,0.6,0.6,4.5,4.8,...,92.6,85.7,72.9,5.5,5.9,13,False,False,False,True
1,0.9,1.8,1.3,3.1,0.9,1.6,0.8,0.6,0.8,1.1,...,69.4,77.4,33.7,1.9,5.5,18,False,False,False,True
2,2.9,2.1,0.8,5.8,0.7,0.5,1.1,0.9,4.3,1.0,...,84.2,84.5,74.5,17.7,17.5,0,False,True,False,False
3,5.4,2.6,3.2,5.7,5.2,2.3,0.5,8.2,1.7,1.7,...,35.6,60.2,34.8,7.5,4.4,16,False,True,False,False
4,0.9,0.6,1.1,1.7,0.5,0.7,0.5,0.5,0.6,0.9,...,74.3,64.2,65.6,11.7,14.6,1,False,True,False,False

In [311]:
lasso_pipe.fit(X_train, y1_train)
y12 = lasso_pipe.predict(X_test)
lasso_pipe.fit(X_train, y2_train)
y24 = lasso_pipe.predict(X_test)
lasso_pipe.fit(X_train, y3_train)
y48 = lasso_pipe.predict(X_test)
y12

array([ 4.58572534,  2.61618183, 16.72358375, ...,  5.85964098,
       12.25955314, 12.28329424], shape=(3247,))

In [319]:
from datetime import date
id = df_challenge['Id']
day = date.today().strftime("%d%m%Y")
dfy12 = pd.DataFrame()
dfy12['Id'] = id
dfy12['target_tre200h0_plus12h'] = y12

dfy24 = pd.DataFrame()
dfy24['Id'] = id
dfy24['target_tre200h0_plus24h'] = y24

dfy48 = pd.DataFrame()
dfy48['Id'] = id
dfy48['target_tre200h0_plus48h'] = y48

dfy = pd.DataFrame()
dfy['Id'] = id
dfy['target_tre200h0_plus12h'] = y12
dfy['target_tre200h0_plus24h'] = y24
dfy['target_tre200h0_plus48h'] = y48

dfy12.to_csv("lasso_y12.csv", index=False, encoding="utf-8")
dfy24.to_csv(f"submission{day}.csv", index=False, encoding="utf-8")
dfy48.to_csv("lasso_y48.csv", index=False, encoding="utf-8")
dfy.to_csv("lasso_yAll.csv", index=False, encoding="utf-8")

In [313]:
dfy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3247 entries, 0 to 3246
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       3247 non-null   int64
 1   target_tre200h0_plus12h  3247 non-null   float64
 2   target_tre200h0_plus24h  3247 non-null   float64
 3   target_tre200h0_plus48h  3247 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 101.6 KB

Ne Fonctionne pas pour les tests finaux

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error, r2_score

# y12
print('################### Prediction 12H')
print(f"Variance de y : {np.var(y1)}" )
print(f"Ecart-type de y : {np.std(y1)}")
print(f"MSRE_test : {root_mean_squared_error(y1, y12)}")
print(f"Test R2_score (accuracy):{r2_score(y1, y12)}\n")
# y24

print('################### Prediction 24H' )
print(f"Variance de y : {np.var(y2)}" )
print(f"Ecart-type de y : {np.std(y2)}")
print(f"MSRE_test : {root_mean_squared_error(y2, y24)}")
print(f"Test R2_score (accuracy):{r2_score(y2, y24)}\n")
# y48

print('################### Prediction 48H')
print(f"Variance de y : {np.var(y3)}" )
print(f"Ecart-type de y : {np.std(y3)}")
print(f"MSRE_test : {root_mean_squared_error(y3, y48)}")
print(f"Test R2_score (accuracy):{r2_score(y3, y48)}\n")